<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Quiz 3</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: dai xin
- ID: 1901212570

In [1]:
import numpy as np

<div class="alert alert-warning">
<b>QUESTION 1: </b> 

1, Define a list: `list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`

2, Use list comprehension to create a new list which contains elements larger or equal to 3 in `list_1`. Print the new list, the expected output would be: `[3, 4, 5, 6, 7, 8, 9, 10]`
</div>

In [4]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list_num = [i for i in list_1 if i>=3]
print(list_num)


[3, 4, 5, 6, 7, 8, 9, 10]


<div class="alert alert-warning">
<b>QUESTION 2: </b> 

1, Define a dictionary with fruit names and prices: `prices = {"banana":0.5, "apple":1, "kiwi":1, "orange":0.8, "pineapple":3.2}`

2, Please calculate the average price of the fruits and print the result. The expected output is `1.3`

In [72]:
prices = {"banana":0.5, "apple":1, "kiwi":1, "orange":0.8, "pineapple":3.2}
for index value in prices:
    x=sum(value)/len(index)
print(x)


SyntaxError: invalid syntax (<ipython-input-72-9ef992381d1a>, line 2)

<div class="alert alert-warning">
<b>QUESTION 3: </b> 

Using a <b>while</b> loop, calculate the cube sum of the first 10 natural numbers and print the result.

$1^{3}+2^{3}+3^{3}+4^{3}+5^{3}+6^{3}+7^{3}+8^{3}+9^{3}+10^{3}$

<br>
The expected result would be $3025$.
</div>

In [10]:
z=0
i=0
while i <=10:
    i=i**3
    z=z+i
    i=i+1
print(z)
    

738


<div class="alert alert-warning">

<b>QUESTION 4:</b>

Create a $3$ $x$ $7$ array with integers ranging from 200 to 0 with a step of 10 (in descending order).

Print the array, the expected output is:
    
```
[[200 190 180 170 160 150 140]
 [130 120 110 100  90  80  70]
 [ 60  50  40  30  20  10   0]]```
 
</div>

In [14]:
import numpy as np
print(np.arange(200,-1,-10).reshape(3,7))

[[200 190 180 170 160 150 140]
 [130 120 110 100  90  80  70]
 [ 60  50  40  30  20  10   0]]


<div class="alert alert-warning">
<b>QUESTION 5:</b> 
    
Please print the following string using **ONE LINE** of code:
    
```
Dear Diary,
Today's quiz was "great".
I'm looking forward to the next week's "challenges".
```

</div>

In [18]:
print('Dear Diary \n Today's quiz was "great" \n  I\'m looking forward to the next week\'s "challenges" ')

SyntaxError: invalid syntax (<ipython-input-18-c39ad8d2c212>, line 1)

<div class="alert alert-warning">
<b>QUESTION 6:</b>

Create a function called `factor_div` wich takes two arguments `x` and `y`. The function returns `x` divided by `y` as an **integer**.

If `y` is not a factor of `x` (`x` can't be divided by `y` without a remainder), the function will raise an `AssertionError` with the message: `Please make sure that the second argument is a factor of the first argument.`
</div>

In [19]:
def factor_div(x,y):
    try:
        return int(x/y)
    except ValueError:
        return error
    
print(factor_div(3,2))


1


<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define a list: `list_b = [10, 100, 1000, 10000, 100000, 1000000, 1000000]`

2, Print a slice of `list_b` with the 3 middle elements. The expected output is: 
    
```
[1000, 10000, 100000]```

</div>

In [20]:
list_b = [10, 100, 1000, 10000, 100000, 1000000, 1000000]
print(list_b[2:5])

[1000, 10000, 100000]


<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
1, Define an array: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)`

2, Replace the elements in the middle row with 8s. Print the new array, the expected output is:
```
[[0 1 2]
 [8 8 8]
 [6 7 8]]```

</div>

In [25]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)
arr[1,:]=8
print(arr)

[[0 1 2]
 [8 8 8]
 [6 7 8]]


<div class="alert alert-warning">
<b>QUESTION 9:</b>
    
1, Define two arrays:
    
```python
prices_array = np.array([170.12,  93.29,  55.28, 145.3 , 171.81,  59.5 , 100.5 ]) 
earnings_array = np.array([ 9.2 ,  5.31,  2.41,  5.91, 15.42,  2.51,  6.79])```
    
`prices_array` contains the stock prices for 7 companies and `earnings_array` contains their earnings. 

2, Create a new array called `PE` which contains the PE (price to earnings) ratios for those companies. The PE ratio is calculated by dividing stock price by earnings. Print the new array, the expected output is:
```
[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]```    

</div>

In [27]:
prices_array = np.array([170.12,  93.29,  55.28, 145.3 , 171.81,  59.5 , 100.5 ]) 
earnings_array = np.array([ 9.2 ,  5.31,  2.41,  5.91, 15.42,  2.51,  6.79])
PE=prices_array /earnings_array
print(PE)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Select out a subset of all even rows from `arr` and print it. The expected output is:
```
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]```

</div>

In [35]:
import numpy as np
arr = np.arange(21).reshape(7,3)
print(arr[[1, 3, 5,]])


[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]


<div class="alert alert-warning">
<b>QUESTION 11:</b>
    
1, Define an array: `data_arr = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])`

2, For each row in the array, apply the following formula:
    
$x_{1}\times2 + x_{2}\times5 + x_{3}\times3$
    
For instance, if you apply the formula to the first row, you will get 39 ($10\times2 + 2\times5 + 3\times3$).

3, A one-dimensional array will be created after applying the formula to each row. Print the new array, the expected output is:
```
[ 39  26 186  39]```
</div>

In [41]:
import numpy as np
data_arr = np.array([[10,2,3],[1,3,3],[2,34,4],[5,4,3]])
print(data_arr)
data_arr=data_arr[:,:1]*2
print(data_arr)

[[10  2  3]
 [ 1  3  3]
 [ 2 34  4]
 [ 5  4  3]]
[[20]
 [ 2]
 [ 4]
 [10]]


<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
1, Define an array: 
    
```python
arr2d = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])```

2, Sort the values in each column of `arr2d` in ascending order. Print the new array, the expected output is:
```
[[ 2  8  1  2]
 [ 5 10  2  3]
 [ 9 11  5  7]
 [17 13  8 10]
 [20 14 17 14]]```

</div>

In [43]:
import numpy as np
arr2d = np.array([[ 2, 10,  8,  7],
                  [20, 13,  5,  2],
                  [17, 14,  1,  3],
                  [ 9, 11, 17, 10],
                  [ 5,  8,  2, 14]])
arr2d.sort(axis=0)
print(arr2d)

[[ 2  8  1  2]
 [ 5 10  2  3]
 [ 9 11  5  7]
 [17 13  8 10]
 [20 14 17 14]]


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Print the array below by indexing `arr`.

```    
[[ 7  8]
 [10 11]
 [13 14]]```

</div>

In [46]:
arr = np.arange(21).reshape(7,3)
print(arr[2:5,1:3])

[[ 7  8]
 [10 11]
 [13 14]]


<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define an array: `arr = np.arange(21).reshape(7,3)`

2, Replace the odd numbers in `arr` with 1s. Print the new array, the expected output is:
```
[[ 0  1  2]
 [ 1  4  1]
 [ 6  1  8]
 [ 1 10  1]
 [12  1 14]
 [ 1 16  1]
 [18  1 20]]```
</div>

In [47]:
arr = np.arange(21).reshape(7,3)
arr[arr%2!=0] = 1
print(arr)

[[ 0  1  2]
 [ 1  4  1]
 [ 6  1  8]
 [ 1 10  1]
 [12  1 14]
 [ 1 16  1]
 [18  1 20]]


<div class="alert alert-warning">
<b>QUESTION 15:</b>
    
1, Define a string: `string_NY = 'You know New York, you need New York, you know you need unique New York.'`

2, Write code to count the number of times `New York` occurs in the string `string_NY`. Print the result, the correct output is `3`.
</div>

In [56]:
string_NY = 'You know New York, you need New York, you know you need unique New York'
inital_list = string_NY.replace(',',' ').replace('.', ' ').split()
print(inital_list)
x=inital_list.count('New')
print(x)


['You', 'know', 'New', 'York', 'you', 'need', 'New', 'York', 'you', 'know', 'you', 'need', 'unique', 'New', 'York']
3


<div class="alert alert-warning">
<b>QUESTION 16: </b> 

Create a $5\times5$ array with 0's on the border and 1's inside (as shown below). Print the array.
```
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]   
```
</div>

In [57]:
arr = np.zeros((5,5))
arr[1:4,1:4] = 1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


<div class="alert alert-warning">
<b>QUESTION 17: </b> 

1, Create a function called `divisible_by_9` using `lambda` statement which returns the argument divided by `9` if the number can be divided by `9` without a remainder. If the argument can't be divided by 9 without a remainder the function should return `0.0` (float number).
    
2, Define a list: `numbers = [9, 15, 18, 22, 27, 42]`

3, Apply the function `divisible_by_9` to all the elements in list `numbers` using `map` function.

4, Print the new list, the expected output is: `[1.0, 0.0, 2.0, 0.0, 3.0, 0.0]`
</div>

In [ ]:
def divisible_by_9(x):
    if x
    return x/9

my_func(lambda x:2*x*x,5)

<div class="alert alert-warning">
<b>QUESTION 18:</b>

Define a function named `sum_arr` which takes an array with numbers as the argument. The funtion would calculate the sum of the elements in the array and print `The sum of the elements in the array is: ` followed by the result.
 
If we call the function with array `np.array([[1,2,3],[4,5,6],[7,8,9]])`, it would print:

`The sum of the elements in the array is: 45`

In [67]:
def sum_arr(x):
    return sum(sum(x))
sum_arr(np.array([[1,2,3],[4,5,6],[7,8,9]]))

45

<div class="alert alert-warning">
<b>QUESTION 19: </b> 
    
Define a list: `list_num = [1, 3, 5, 6, 8]`

Sort the list by the ascending order of the absolute difference between the element and the number `5`. Print the new list, the expected output is:

`[5, 6, 3, 8, 1]`
</div>

In [71]:
list_num = [1, 3, 5, 6, 8]
result.sort(abs(x-5))
print(result)

TypeError: sort() takes no positional arguments

<div class="alert alert-warning">
<b>QUESTION 20: </b> 

Define a dictionary: 
    
`Shares = {'James':2359, 'Robert':4032, 'Nicolas':1020, 'Louis':2500, 'Bernard': 5538, 'Logan':1330}`

For the dictionary keys end with letter `s`, update the corresponding dictionary values to `2020`. Print the updated dictionary, the expected output would be:

`{'James': 2020, 'Robert': 4032, 'Nicolas': 2020, 'Louis': 2020, 'Bernard': 5538, 'Logan': 1330}`
</div>

In [68]:
Shares = {'James':2359, 'Robert':4032, 'Nicolas':1020, 'Louis':2500, 'Bernard': 5538, 'Logan':1330}
for index,value in Shares:
    if s in index:
        value=2020
print(Shares)
    

ValueError: too many values to unpack (expected 2)